### ISSUE TITLE
Implementar DTOs

### ISSUE THREAD

**Issue by adelsonsljunior** [zeMatheusLira/project-springboot#1]
### O DTO (Objeto de Transferência de Dados) é uma técnica para passar objetos com deterninados campos entre as camadas.

É uma boa prática usar DTOs nas Resquest e Responses passando somente os campos necessários

**Exemplo de Request:**
~~~json
{
    "username": "marceline",
    "email": "marceline1@ooo.com",
    "password": "12345678"
}
~~~

**Exemplo de Response:**
~~~json
{
    "id": 1
    "username": "marceline",
    "email": "marceline1@ooo.com"
}
~~~

(a senha de um usuário não pode ser retornada na Response)

### Recomendações:

+ Use Records para criar os DTOs
+ Nas entidades crie um construtor que vai receber um dto que vai passar seus atributos para a entidade
+ Nas entidades (caso julgue necesário) crie um método `toResponse` que retornará um DTO
+ Uma outra opção é usar o `MapStruct`, é uma biblioteca muito usada para conversão, você pode dar uma pesquisa (nunca cheguei a usar)
+ Uma boa prática é os Services receberem e devolverem DTOs

**Comment by zeMatheusLira** [comment]
Implementação dos DTOs realizada.
